### ISSUE TITLE
[要望]'ok’のノーテーションを追加していただけませんか？

### ISSUE THREAD

**Issue by pawa-** [moznion/Test-Synopsis-Expectation#4]
はじめまして。
もしよろしければ 'ok' のノーテーションを追加していただけませんか？
よろしくお願いいたします。
## 

pawa

**Comment by moznion** [comment]
(English follows Japanese)

`ok`の記法ですが，どういう使い方だと便利ですか？

```
my $num = 1; # => ok == 1
my $string = "hello"; # => ok eq "hello"
```

みたいな使い方でしょうか？ (なんだか見た目微妙ですね…)
どういった使い方をしたいか教えて頂けると嬉しいです。

## 

How do you think that you feel useful about `ok` notation?

```
my $num = 1; # => ok == 1
my $string = "hello"; # => ok eq "hello"
```

Like this example? (Umm, it looks not smart...)
Could you suggest me about how to use it?

**Comment by pawa-** [comment]
返信ありがとうございます。

以下の２行が equivalent であると嬉しいです。
epubcheck('epub/valid.epub')->is_valid; # => ok
ok( epubcheck('epub/valid.epub')->is_valid );

よろしくお願いいたします。

## 

pawa

**Comment by moznion** [comment]
なるほど，ありがとうございます．
しかし，`ok`だと誤解を生みそうなので (`Test::More`に同名のメソッドが定義されていて，こちらは死ぬほど汎用的に使える)，新しいキーワード`success`を導入しようと思いましたがどうでしょうか。

e.g.

```
epubcheck('epub/valid.epub')->is_valid; # => success
```

## 

Thanks, I see.

However, users may panic if this module uses `ok` keyword because `Test::More` defines the same name function, and it can use as multipurpose; so I think I should define new keyword `success`.

e.g.

```
epubcheck('epub/valid.epub')->is_valid; # => success
```

How do you feel?

**Comment by pawa-** [comment]
ありがとうございます。
問題がなければ、それでお願いいたします。 m(__)m

## 

pawa

**Comment by moznion** [comment]
実装致しました。v0.11から利用可能です。
